/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testebtnaval;

import java.awt.Color;
import java.awt.GridLayout;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class TelaTeste extends javax.swing.JFrame {

    public boolean Pronto = false;
    public ServerBtInterface servidor;
    public Tile[][] Matriz, MatrizInimigo;
    public ClientInterface client;
    public int tamanho = 0;
    public int qtdeVida = 0;
    public int pontos = 0;
    public int qtdS = 0, qtdPA = 2, qtdCT = 0, qtdNT = 0;

    public int getQtdeVida() {
        return qtdeVida;
    }

    public void setScore(int value) {
        jLabelScore.setText(String.valueOf(value));
    }

    public int getScore() {
        return Integer.parseInt(jLabelScore.getText());
    }

    public void setQtdeVida(int qtdeVida) {
        this.qtdeVida = qtdeVida;
    }

    /**
     * Creates new form TelaTeste
     */
    public TelaTeste() {
        initComponents();
        jPanelTabMatriz.setLayout(new GridLayout(10, 10));
        jPanelTabMatrizInimigo.setLayout(new GridLayout(10, 10));
        Matriz = new Tile[10][10];
        MatrizInimigo = new Tile[10][10];
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                Tile tile = new Tile(i, j, this, true, "vazio");
                tile.setText("-");
                Matriz[i][j] = tile;
                jPanelTabMatriz.add(tile);
            }
        }
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                Tile tile = new Tile(i, j, this, true, "vazio");
                tile.setText("-");
                MatrizInimigo[i][j] = tile;
                jPanelTabMatrizInimigo.add(tile);
            }
        }
    }

    public TelaTeste(ServerBtInterface servidor, ClientInterface client) {
        initComponents();
        this.servidor = servidor;
        this.client = client;
        jPanelTabMatriz.setLayout(new GridLayout(10, 10));
        jPanelTabMatrizInimigo.setLayout(new GridLayout(10, 10));
        Matriz = new Tile[10][10];
        MatrizInimigo = new Tile[10][10];
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                Tile tile = new Tile(i, j, this, true, "A");
                tile.setText("-");
                tile.setSize(50, 50);
                Matriz[i][j] = tile;
                jPanelTabMatriz.add(tile);
            }
        }
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                Tile tile = new Tile(i, j, this, true, "A");
                tile.setText("-");
                tile.setSize(40, 40);
                MatrizInimigo[i][j] = tile;
                jPanelTabMatrizInimigo.add(tile);
            }
        }
        setEnemyFields(false);
    }

    public void setEnemyFields(boolean value) {
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                MatrizInimigo[i][j].setEnabled(value);
            }
        }
    }

    public void setFields(boolean value) {
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                Matriz[i][j].setEnabled(value);
            }
        }
    }

    public void setFieldValue(int linha, int coluna, Color color) {
        //Matriz[linha][coluna].setText(Matriz[linha][coluna].tipo);
        Matriz[linha][coluna].setBackground(color);
        //Matriz[linha][coluna].setDisabledIcon(Matriz[linha][coluna].getIcon());
        Matriz[linha][coluna].setText("<html><font color = red>" + Matriz[linha][coluna].tipo + "</font></html>");
    }

    public Tile getTile(int linha, int coluna) {
        return Matriz[coluna][linha];
    }

    public boolean getTileOccupied(int linha, int coluna) {
        if (!Matriz[coluna][linha].tipo.equals("A")) {
            return true;
        } else {
            return false;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelTabMatriz = new javax.swing.JPanel();
        jPanelTabMatrizInimigo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPaneChat = new javax.swing.JEditorPane();
        jButtonEnviar = new javax.swing.JButton();
        jTextFieldTexto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabelScore = new javax.swing.JLabel();
        jButtonGiveUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setText("Seu Campo");

        jPanelTabMatriz.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelTabMatriz.setPreferredSize(new java.awt.Dimension(365, 365));

        javax.swing.GroupLayout jPanelTabMatrizLayout = new javax.swing.GroupLayout(jPanelTabMatriz);
        jPanelTabMatriz.setLayout(jPanelTabMatrizLayout);
        jPanelTabMatrizLayout.setHorizontalGroup(
            jPanelTabMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelTabMatrizLayout.setVerticalGroup(
            jPanelTabMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        jPanelTabMatrizInimigo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelTabMatrizInimigoLayout = new javax.swing.GroupLayout(jPanelTabMatrizInimigo);
        jPanelTabMatrizInimigo.setLayout(jPanelTabMatrizInimigoLayout);
        jPanelTabMatrizInimigoLayout.setHorizontalGroup(
            jPanelTabMatrizInimigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelTabMatrizInimigoLayout.setVerticalGroup(
            jPanelTabMatrizInimigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        jLabel2.setText("Inimigo");

        jLabel3.setText("Status:");

        jLabelStatus.setText("-   - - - - --- - - -");

        jButton1.setText("PA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jEditorPaneChat.setEditable(false);
        jScrollPane1.setViewportView(jEditorPaneChat);

        jButtonEnviar.setText(">");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Pontuação:");

        jLabelScore.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelScore.setForeground(new java.awt.Color(255, 0, 51));
        jLabelScore.setText("0");

        jButtonGiveUp.setText("Desistir");
        jButtonGiveUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGiveUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(433, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelTabMatrizInimigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelScore, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79))
                            .addComponent(jPanelTabMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldTexto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonGiveUp)
                                .addGap(74, 74, 74)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabelScore))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEnviar)))
                    .addComponent(jPanelTabMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTabMatrizInimigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonGiveUp)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelStatus)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.tamanho = 5;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        if (!jTextFieldTexto.getText().isEmpty()) {
            try {
                servidor.sendMessage(this.client.GetName() + ": " + jTextFieldTexto.getText());
                jTextFieldTexto.setText("");
                jTextFieldTexto.grabFocus();
            } catch (RemoteException ex) {
                Logger.getLogger(TelaTeste.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jButtonGiveUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGiveUpActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja desistir?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            try {
                servidor.GiveUp(client);
            } catch (RemoteException ex) {
                Logger.getLogger(TelaTeste.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonGiveUpActionPerformed

    public void UpdateChat(String messages) {
        this.jEditorPaneChat.setText(messages);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTeste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonGiveUp;
    private javax.swing.JEditorPane jEditorPaneChat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelScore;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPanel jPanelTabMatriz;
    private javax.swing.JPanel jPanelTabMatrizInimigo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldTexto;
    // End of variables declaration//GEN-END:variables

    void setStatus(String val) {
        jLabelStatus.setText(val);
    }

    void EstadosMatriz(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
